#!/bin/bash
# AniMind — Cloudflare Tunnel setup script
# Run once on the homeserver. Interactive steps are clearly marked.
# Usage: bash scripts/setup_tunnel.sh

set -euo pipefail

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

info()  { echo -e "${GREEN}[INFO]${NC}  $1"; }
warn()  { echo -e "${YELLOW}[WARN]${NC}  $1"; }
error() { echo -e "${RED}[ERROR]${NC} $1" >&2; exit 1; }
step()  { echo -e "\n${GREEN}══ STEP $1 ══${NC}"; }

TUNNEL_NAME="animind"
CONFIG_DIR="$HOME/.cloudflared"
CONFIG_FILE="$CONFIG_DIR/config.yml"
BACKEND_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/backend"

# ── Step 1: Install cloudflared ───────────────────────────────────────────────
step "1/6 — Install cloudflared"

if command -v cloudflared &>/dev/null; then
    info "cloudflared already installed: $(cloudflared --version 2>&1 | head -1)"
else
    info "Downloading cloudflared (linux-amd64)..."
    ARCH=$(uname -m)
    case "$ARCH" in
        x86_64)  BIN="cloudflared-linux-amd64" ;;
        aarch64) BIN="cloudflared-linux-arm64" ;;
        *)        error "Unsupported architecture: $ARCH" ;;
    esac
    curl -fsSL "https://github.com/cloudflare/cloudflared/releases/latest/download/${BIN}" \
        -o /tmp/cloudflared
    chmod +x /tmp/cloudflared
    sudo mv /tmp/cloudflared /usr/local/bin/cloudflared
    info "Installed: $(cloudflared --version 2>&1 | head -1)"
fi

# ── Step 2: Cloudflare login ──────────────────────────────────────────────────
step "2/6 — Cloudflare login"

if [ -f "$CONFIG_DIR/cert.pem" ]; then
    info "Already authenticated (cert.pem found)"
else
    warn "Opening browser for Cloudflare authentication..."
    warn "After login, select the domain you want to use and click 'Authorize'."
    cloudflared tunnel login
fi

# ── Step 3: Create tunnel ─────────────────────────────────────────────────────
step "3/6 — Create tunnel '$TUNNEL_NAME'"

EXISTING_ID=$(cloudflared tunnel list --output json 2>/dev/null \
    | python3 -c "import json,sys; tunnels=json.load(sys.stdin); \
      match=[t['id'] for t in tunnels if t['name']=='$TUNNEL_NAME']; \
      print(match[0] if match else '')" 2>/dev/null || true)

if [ -n "$EXISTING_ID" ]; then
    TUNNEL_ID="$EXISTING_ID"
    info "Tunnel '$TUNNEL_NAME' already exists: $TUNNEL_ID"
else
    info "Creating tunnel '$TUNNEL_NAME'..."
    OUTPUT=$(cloudflared tunnel create "$TUNNEL_NAME" 2>&1)
    echo "$OUTPUT"
    # Extract UUID only — format: "Created tunnel animind with id <UUID>"
    TUNNEL_ID=$(echo "$OUTPUT" | grep -oP '[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}' | head -1)
    if [ -z "$TUNNEL_ID" ]; then
        error "Could not parse tunnel UUID from output. Check output above."
    fi
    info "Tunnel created: $TUNNEL_ID"
fi

CREDENTIALS_FILE="$CONFIG_DIR/${TUNNEL_ID}.json"

# ── Step 4: Write config.yml ──────────────────────────────────────────────────
step "4/6 — Write ~/.cloudflared/config.yml"

mkdir -p "$CONFIG_DIR"

# Ask for hostname if not set
if [ -z "${ANIMIND_HOSTNAME:-}" ]; then
    echo ""
    warn "Enter the public hostname for the API (e.g. api.yourdomain.com):"
    read -r ANIMIND_HOSTNAME
fi

cat > "$CONFIG_FILE" <<EOF
# AniMind — Cloudflare Tunnel config
# Generated by scripts/setup_tunnel.sh

tunnel: ${TUNNEL_ID}
credentials-file: ${CREDENTIALS_FILE}

ingress:
  - hostname: ${ANIMIND_HOSTNAME}
    service: http://localhost:8000
    originRequest:
      # Forward Host header so FastAPI CORS sees the real hostname
      httpHostHeader: "${ANIMIND_HOSTNAME}"
  # Catch-all: reject everything else
  - service: http_status:404
EOF

info "Config written to $CONFIG_FILE"
cat "$CONFIG_FILE"

# ── Step 5: Add DNS CNAME ─────────────────────────────────────────────────────
step "5/6 — Route DNS"

info "Adding CNAME ${ANIMIND_HOSTNAME} → Cloudflare tunnel..."
cloudflared tunnel route dns "$TUNNEL_NAME" "$ANIMIND_HOSTNAME"

# ── Step 6: Install systemd service ──────────────────────────────────────────
step "6/6 — Install systemd services"

# Find the animind conda env uvicorn
UVICORN_BIN=$(conda run -n animind which uvicorn 2>/dev/null || \
              find "$HOME" -path "*/animind/bin/uvicorn" 2>/dev/null | head -1 || \
              echo "$(which uvicorn)")
info "uvicorn binary: $UVICORN_BIN"

# Backend service
sudo tee /etc/systemd/system/animind-backend.service > /dev/null <<EOF
[Unit]
Description=AniMind FastAPI Backend
After=network.target docker.service
Wants=docker.service

[Service]
Type=simple
User=$(whoami)
WorkingDirectory=${BACKEND_DIR}
ExecStart=${UVICORN_BIN} app.main:app --host 127.0.0.1 --port 8000 --workers 1
Restart=on-failure
RestartSec=5s
Environment="PATH=$(conda run -n animind printenv PATH 2>/dev/null || echo $PATH)"
EnvironmentFile=${BACKEND_DIR}/.env

[Install]
WantedBy=multi-user.target
EOF

# Cloudflare Tunnel service
sudo tee /etc/systemd/system/cloudflared-animind.service > /dev/null <<EOF
[Unit]
Description=Cloudflare Tunnel — AniMind
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=$(whoami)
ExecStart=/usr/local/bin/cloudflared tunnel --config ${CONFIG_FILE} run ${TUNNEL_NAME}
Restart=on-failure
RestartSec=5s
# Quiet cloudflared's noisy default logger
Environment="TUNNEL_LOGLEVEL=warn"

[Install]
WantedBy=multi-user.target
EOF

sudo systemctl daemon-reload
sudo systemctl enable animind-backend.service
sudo systemctl enable cloudflared-animind.service

info "Services enabled. Starting now..."
sudo systemctl restart animind-backend.service
sleep 3
sudo systemctl restart cloudflared-animind.service
sleep 2

# ── Verification ──────────────────────────────────────────────────────────────
echo ""
info "═══════════════════════════════════════════"
info "Verification"
info "═══════════════════════════════════════════"

echo ""
echo "▶ Backend status:"
sudo systemctl status animind-backend.service --no-pager -l | head -20

echo ""
echo "▶ Tunnel status:"
sudo systemctl status cloudflared-animind.service --no-pager -l | head -20

echo ""
echo "▶ Local health check:"
curl -si http://localhost:8000/health | head -5

echo ""
info "Public URL: https://${ANIMIND_HOSTNAME}/health"
info "Test with:"
echo "  curl https://${ANIMIND_HOSTNAME}/health"
echo ""
info "To watch logs:"
echo "  journalctl -u animind-backend -f"
echo "  journalctl -u cloudflared-animind -f"
